### ISSUE TITLE
I can't play that game on the newest Switch FW-Version. (v11.0.1)

### ISSUE THREAD

**Issue by Vadenimo** [retronx-team/supermariowar-nx#1]
Hey, I can't play the game on the newest Switch-Version. I don't know why, but I hope that will be fixed.

**Comment by p-sam** [comment]
Hey you gave no details as to why you can't play it, I'm not sure I can fix "I don't know why" without more explanation

What's your atmosphere version? did you get the latest release from here? and can you upload the logs here? It should be a file named smw.log or smth like that in the your supermariowar game folder

**Comment by Vadenimo** [comment]
My problem is fixed now, I redownloaded the game, and it works now. Sorry for bothering!

**Comment by p-sam** [comment]
cool then, closing the issue

**Comment by ImanCol** [comment]
This really doesn't work. I have downloaded it from everywhere and it does not run, it goes black screen from NSP and from .NRO it returns me to Homebrew. Fix it please

11.0.0
SXOS  3.1
Atmosphere 19.x
