### ISSUE TITLE
Game crashes when trying to launch

### ISSUE THREAD

**Issue by Crissley10** [retronx-team/supermariowar-nx#2]
I'm running firmware 11.0.1, Atmosphere 19.1, hekate 5.5.5, and when I try to launch Super Mario War, I get a black screen and shortly after I get taken back to my hbmenu. I have deleted and reinstalled the game a couple of times with no luck of getting the issue fixed.

**Comment by p-sam** [comment]
I've been using SMW with no issue on AMS 19.1, i'm using hekate 5.5.5 too. You could try checking if everything is in place, or if there's no custom sysmodule interfering, and maybe update to HOS 12 too

**Comment by Crissley10** [comment]
I have updated to 12.0.1 two days ago, atmosphere 19.1 hekate 5.5.5, and it still crashes

**Comment by p-sam** [comment]
I'm not sure what's the issue, I can't reproduce any crash on my end. Please send the logfile of the last run, should be at `/switch/smw/smw.log`

**Comment by Crissley10** [comment]
Here's the log:
https://drive.google.com/file/d/1NvBjyC-PKnWigCaqhX75JyG5kQfElVAR/view?usp=sharing

**Comment by p-sam** [comment]
Yeah the game complains about maps being missing, check that you copied the files correctly

Edit: If it helps, you can also try to run the Archive bit fix tool in Hekate

**Comment by Crissley10** [comment]
Alright well I reinstalled it once again and it decided to work this time. Not sure why reinstalling it all those other times didn't work but at least it's working now. Thanks for the help 👌
