### ISSUE TITLE
Single HID line broken

### ISSUE THREAD

**Issue by nogarcia** [retronx-team/supermariowar-nx#3]
[libnx v4.0.0](https://github.com/switchbrew/libnx/releases/tag/v4.0.0) redesigned the input system, which now breaks the build with _one_ enum being renamed. It doesn't look like the redesign breaks anything else — much of the input is abstracted away in SDL — but [this line](https://github.com/retronx-team/supermariowar-nx/blob/ac2b5f2febe316e30ed9d741e7d3a19dc1e8ff3c/supermariowar/src/smw/platform/switch.c#L40) no longer compiles. https://github.com/retronx-team/supermariowar-nx/blob/ac2b5f2febe316e30ed9d741e7d3a19dc1e8ff3c/supermariowar/src/smw/platform/switch.c#L40

It looks like this enum was just renamed to `HidNpadJoyHoldType_Horizontal`, and it builds when I change that line. I'll test to see if it actually works.

**Comment by nogarcia** [comment]
Yep, looks like that change is all that's necessary to fix it.

**Comment by p-sam** [comment]
Yeah this is a common occurence as libnx breaking changes are frequent, I usually try to keep the platform-specific code to a minimum
