### ISSUE TITLE
Emulator Compatibility

### ISSUE THREAD

**Issue by VerKmusic** [retronx-team/supermariowar-nx#4]
Is there a way to play it on a emulator?, everytime that i load the game in ´´Ryujinx´´(Nintendo Switch emulator) it abruptly closes, it´s probably because the NRO file is separated from the data folder,therefore it loads the file but without the content.

It would be great if you guys could  any time soon create  a version with all the content in just one file(the game as a whole in one file), so for emulator users to have a possibility to have fun with it :D.

Have a nice day.

**Comment by VerKmusic** [comment]
https://user-images.githubusercontent.com/87917543/126884238-83504baa-3b4e-4e9e-8ad9-7f426931f404.mp4

**Comment by p-sam** [comment]
There probably should be a way to set it up properly. Anyway, this seems more like emu user support and/or emu compat problems, so quite out of scope for this project. Why not just play the original PC ver it's ported from?
