### ISSUE TITLE
Game crashing on launch

### ISSUE THREAD

**Issue by mrmeyers01** [retronx-team/supermariowar-nx#5]
Firmware 15.0.1
Atmosphere 1.4.1

Downloaded the latest from the HB App Store, will not launch

**Comment by eadmaster** [comment]
same here, fixed by reinstalling manually via FTPd, i guess it is a bug with the App store: 
https://github.com/retronx-team/supermariowar-nx/issues/2

**Comment by impeeza** [comment]
did installing from GitHub solve the issue?

**Comment by eadmaster** [comment]
> did installing from GitHub solve the issue?

Yes.

**Comment by impeeza** [comment]
excellent, so can be closed :P

**Comment by mrmeyers01** [comment]
Just installed it with DBI and it works perfectly, seems to be a homebrew store issue after all. Thanks!
